# Project choice justification
Brown-Iannuzzi et al. (2016) examines how opposition to welfare may be driven by negative stereotypes of welfare recipients, particularly of being African American, incompetent, and lazy. In my research agenda, I am broadly interested in ways (a) to improve the effectiveness of cash assistance as a welfare program, e.g. basic income, for recipients and (b) to increase citizen support for evidence-based welfare programs. In this replication project, I would be able to advance these objectives by understanding which types of stereotype threats welfare recipients face and what stereotypes and cultural ideas influence citizen support for cash-based welfare. In particular, I am interested in examining the particularly American cultural ideas of deservingness and competence as requirements for receiving welfare, which are two of the primary characteristics asssessed in this study. I ultimately hope to translate this knowledge to design and/or frame welfare interventions so that they minimize social identity threats faced by welfare recipients and to design framings of evidence-based welfare programs to increase their support from citizens. 

# Stimuli and procedures and anticipated challenges
I would replicate the findings of the within-subjects experimental Study 3 on Mechanical Turk (n=229). These participants will be shown faces generated from Studies 1 and 2, which were generated to be typical faces of welfare recipients and of non-welfare recipients and rated, by separate samples, on perceived visual characteristics and traits, such as race, likeability, laziness, competency, and agency. Participants will be see the stereotypic faces of welfare recipients, of non-welfare recipients, and of fuzzy fillers. They will be told that some of the images are of responsible recipients of welfare while others are of irresponsible recipients. They will rate the faces on perceived race, competence, laziness, and these measures will be the primary dependent variables. They will also rate the faces on responsibility in general, in use of food stamps, and in use of cash assistance and will lastly be asked about their support for giving the pictured person food stamps and cash assistance. 

All of the materials, including the images and scales, for this study are published freely online at [Mental Representations of Welfare Recipients](https://dx.doi.org/10.6084/m9.figshare.c.3468495.v2). For this reason, I do not anticipate any major challenges in terms of running the experiment itself. It may be difficult to replicate a similar study composition (on race in particular) within the given time frame of the study. I would also want to make sure that the replication adhered to features of the original study in terms of time limitations on showing faces to participants and the ordering of questions. I would hope to receive such details via correspondence with the original researchers. 

